NureLecturerManager.WEB/Controllers/MVC/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.AccessControl;
using System.Web;
using System.Web.Mvc;
using NLM.BLL.DTO;
using NLM.BLL.Interfaces;
using NLM.BLL.Services;
using NLM.WEB.Filters;

namespace NLM.WEB.Controllers
{
    public class SharedController : Controller
    {
        //public SharedController(/*IAccountService account*/)
        //{
        //    //accountS = account;
        //}

        //// GET: Shared
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ActionResult About()
        {
            
            return View();
        }
    }
}

NureLecturerManager.WEB/Controllers/Old/DisciplineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NLM.BLL.DTO;
using NLM.WEB.Models.Lecturer;
using NLM.BLL.Interfaces;
using NLM.BLL.Exceptions;
using System.IO;
using NLM.WEB.Filters;
using NLM.BLL.DTObjects;
using NLM.WEB.Filters.MVC;

namespace NLM.WEB.Controllers
{
    [AuthenticationFilter]
  
    [OnExceptionFilter]
    public class DisciplineController : Controller
    {
        private IDisciplineService discService = DependencyResolver.Current.GetService<IDisciplineService>();
        private IControlPointService controlPointService = DependencyResolver.Current.GetService<IControlPointService>();
        private IControlService controlService = DependencyResolver.Current.GetService<IControlService>();
        private IHelpService helpService = DependencyResolver.Current.GetService<IHelpService>();
        private IAccountService accountService = DependencyResolver.Current.GetService<IAccountService>();

        private const string ADMIN_TYPE = "ADMIN";
        private const string LECTURER_TYPE = "LECTURER";
        private const string STUDENT_TYPE = "STUDENT";

        ////GET: Discipline
        //public ActionResult Index()
        //{
        //    //if (Session["User"] == null)
        //    //    return RedirectToAction("Login", "Account", null);

        //    Session["Placement"] = "Disciplines";
        //    string type = (string)Session["Type"];
        //}

        [AuthorizeFilter("ADMIN")]
        public ActionResult AdminIndex()
        {
                return View();
        }

        [AuthorizeFilter("STUDENT")]
        public ActionResult StudentIndex()
        {
                return View();
        }

        [AuthorizeFilter("LECTURER")]
        public ActionResult LecturerIndex()
        {
            if ((string)Session["Type"] != LECTURER_TYPE)
                return RedirectToAction("Index");
            else
                return View();
        }

        public JsonResult GetAdminModel()
        {
            if ((string)Session["Type"] != ADMIN_TYPE)
                return Json("Ошибка типа пользователя.", JsonRequestBehavior.AllowGet);

            DisciplineAdminViewModel model = new DisciplineAdminViewModel();
            UserDTO user = (UserDTO)Session["User"];
            model.Disciplines = new List<DisciplineDTO>();
            model.DFYs = new Dictionary<string, ICollection<DisciplineForYearsStudentViewModel>>();
            model.ControlPoints = new Dictionary<string, ICollection<ControlPointDTO>>();
            model.WorkTypes = new Dictionary<string, ICollection<WorkTypeDTO>>();

            //   1. Gather Disciplines.
            
            model.Disciplines = discService.GetAllDisciplines();

            if (model.Disciplines.Count == 0)
            {
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            // /2. Gather DFYs

            var discIds = model.Disciplines.Select(d => d.DisciplineId);

            foreach (var disc in discIds)
            {
                // 3.От них собираем DisciplinesForYearStudentsViewModel.

                ICollection<DisciplineForYearDTO> discsForYear = discService.SearchDisciplineForYear(discId: disc);

                if (discsForYear.Count == 0)
                {
                    continue;
                }

                string sId = disc.ToString();
                model.DFYs.Add(sId, discsForYear.Select(dy => new DisciplineForYearsStudentViewModel()
                {
                    Semester = dy.Semester,
                    Year = dy.Year,
                    DFYId = dy.DisciplineForYearId,
                    LecturerNames = accountService.GetLecturersNames(dy.LecturerIds),
                    AssistantsNames = accountService.GetLecturersNames(dy.AssistantsIds)
                }).ToList());

                // 3. 

                // 4.От DisciplinesForYear собираем CPs

                foreach (var dfy in model.DFYs[disc.ToString()])
                {
                    var controlPoints = controlPointService.SearchControlPoints(dfy.DFYId);
                    if (controlPoints.Count != 0)
                    {
                        model.ControlPoints[dfy.DFYId.ToString()] = controlPoints; // Control Points
                    }
                    else
                    {
                        continue;
                    }

                    // /4.


                    //    5.От них - WorkTypes.
                    //    6.От них - Materials.

                    foreach (var point in model.ControlPoints[dfy.DFYId.ToString()])
                    {

                        var workTypes = controlService.SearchWorkType(DFYId: point.ControlPointId);

                        if (workTypes.Count == 0)
                        {
                            continue;
                        }
                        //model.WorkTypes[point.ControlPointId.ToString()] = workTypes; // Control Points
    

                        //foreach (var defaultWorkType in model.WorkTypes[point.ControlPointId.ToString()])
                        //{

                        //    var materials = helpService.SearchMaterials(WorkTypeId: defaultWorkType.WorkTypeId);

                        //    if (materials.Count == 0)
                        //    {
                        //        continue;
                        //    }
                        //    model.Materials[defaultWorkType.WorkTypeId.ToString()] = materials; // Control Points

                        //}
                    }
                }

            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetLecturersModel()
        {
            if ((string)Session["Type"] != LECTURER_TYPE)
                return Json("Ошибка типа пользователя.", JsonRequestBehavior.AllowGet);

            LecturerDisciplineMainViewModel model = new LecturerDisciplineMainViewModel();
            UserDTO user = (UserDTO)Session["User"];
            int lecturerId = user.UserId;
            String year = (string)Session["Year"];
            Int32 semester = Convert.ToInt32(Session["Semester"]);

            ICollection<DisciplineForYearDeepDTO> discs = discService.GetDisciplinesForLecturerDeep(lecturerId);  // Disciplines
            if (discs.Count == 0)
            {
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            // Forming model.DFYs

            foreach (var disc in discs.Where(dfy => dfy.Year == year && dfy.Semester == semester))
            {
                model.Disciplines.Add(new DisciplineDFYLecturerViewModel()
                {
                    DFYId = disc.DisciplineForYearId,
                    DisciplineName = disc.DisciplineName,
                    IsCourseProject = disc.IsCourseProject,
                    LecturerNames = accountService.GetLecturersNames(disc.LecturerIds),
                    AssistantsNames = accountService.GetLecturersNames(disc.AssistantsIds),
                    Semester = disc.Semester,
                    Year = disc.Year,
                    IsAdmin = discService.IsAdmin(disc.DisciplineForYearId, lecturerId)
                });

                var controlPoints = controlPointService.SearchControlPoints(disc.DisciplineForYearId);
                if (controlPoints.Count == 0)
                {
                    continue;
                }
                model.ControlPoints[disc.DisciplineForYearId.ToString()] = controlPoints; // Control Points

                //foreach (var point in model.ControlPoints[disc.DisciplineForYearId.ToString()])
                //{
                //    var workTypes = controlService.SearchWorkType(CpId: point.ControlPointId);
                //    if (workTypes.Count == 0)
                //    {
                //        continue;
                //    }
                //    model.WorkTypes[point.ControlPointId.ToString()] = workTypes; // Control Points

                //    foreach (var defaultWorkType in model.WorkTypes[point.ControlPointId.ToString()])
                //    {
                //        var materials = helpService.SearchMaterials(WorkTypeId: defaultWorkType.WorkTypeId);
                //        if (materials.Count == 0)
                //        {
                //            continue;
                //        }
                //        model.Materials[defaultWorkType.WorkTypeId.ToString()] = materials; // Control Points
                //    }
                //}
            }
            //JsonResult m = Json(model, JsonRequestBehavior.AllowGet);
            //return m;
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        //public JsonResult GetStudentsModel()
        //{
        //    if ((string)Session["Type"] != STUDENT_TYPE)
        //        return Json("Ошибка типа пользователя.", JsonRequestBehavior.AllowGet);

        //    DisciplineViewModel model = new DisciplineViewModel();
        //    UserDTO user = (UserDTO)Session["User"];
        //    model.DFYs = new Dictionary<string, ICollection<DisciplineForYearsStudentViewModel>>();
        //    model.ControlPoints = new Dictionary<string, ICollection<ControlPointDTO>>();
        //    model.WorkTypes = new Dictionary<string, ICollection<WorkTypeDTO>>();


        //    string groupId = accountService.SearchStudent(user.UserId).SingleOrDefault().GroupId;
        //    string year = (string)Session["Year"];
        //    string term = (string)Session["Semester"];

        //    //   1. Собираем Disciplines за этот год.
        //    model.Disciplines = discService.SearchDisciplinesForGroup(groupId, year, Convert.ToInt32(term));

        //    // /1.


        //    // 1
        //    foreach (var disc in model.Disciplines)
        //    {
        //        // 3.От них собираем DisciplinesForYearStudentsViewModel.

NureLecturerManager.WEB/Views/Shared/About.cshtml
@{
    ViewBag.Title = "О нас";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="row margin-top-80px">
    <ol class="breadcrumb">
        <li class="active default-cursor">О нас</li>
    </ol>

    <div class="container">
        <section class="well">
                <h4 class="text-center page-header">Создатели</h4>
                <p class="about-p text-center">Ст. гр. БИКС-14-3</p>
                <p class="about-p text-center">Алексеев Ярослав и Белобров Евгений</p>
                <h4 class="text-center page-header">Благодарности</h4>
                <p class="about-p text-center">Ст. гр. ПИ-14-3 Чачанидзе Сергею за помощь в одном из этапов разработки</p>
                <p class="about-p text-center">Куратору проекта Мазуровой О.А.</p>
                <p class="about-p text-center">Ст. гр. ПИ-14-3 Евгению Попову и его бате за прекрасный сайт metanit.com</p>
                <p class="about-p text-center">Отдельная благодарность Мельниковой Р.В. за финансовую поддержку</p>
                <h4 class="text-center page-header">Техническая поддержка</h4>
                <p class="about-p text-center"><a href="mailto:pv.unnamed@gmail.com">pv.unnamed@gmail.com</a></p>
                <p class="about-p text-center"><a href="mailto:napoleon.emperor@mail.ru">napoleon.emperor@mail.ru</a></p>
                <h4 class="text-center page-header">Счёта WebMoney для пожертвований</h4>
                <p class="about-p text-center">WMZ: Z897510400525</p>
                <p class="about-p text-center">WMU: U333583950473</p>
        </section>
    </div>
</div>

NureLecturerManager.WEB/Views/Shared/Index.cshtml
@using NLM.WEB.Controllers
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout.cshtml";
}

<section class="row">
    <div id="id2" class="col-md-4 col-lg-4 btn btn-slideUp">
        <span class="span-title">Преподавательский состав</span>
    </div>

    <div tabindex="-1" class="col-md-4 col-lg-4">
     
    </div>

    <div class="col-md-4 col-lg-4 btn btn-slideUp">
        <span>Группы</span>
    </div>

    <div class="col-md-4 col-lg-4 btn btn-slideUp">
        <span>Материалы по дисциплинам</span>
    </div>
</section>

NureLecturerManager.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Site")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/")
    @Scripts.Render("~/Scripts/myJs.js")
</head>
<body>
<section class="row">
    <header class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
        <img src="~/Content/images/header-footer.jpg" alt="Загрузка не удалась."/>
    </header>
    @RenderBody()
    <footer class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
        <img src="~/Content/images/header-footer.jpg" alt="Загрузка не удалась."/>
    </footer>
</section>
</body>
</html>

NureLecturerManager.WEB/Views/Shared/_LecturerAdminLayout.cshtml
@using NLM.BLL.DTO
@{
    Layout = null;


    UserDTO user = (UserDTO)Session["User"];
    String login = user.Login;
}

<!DOCTYPE html>

<html>
<head>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/scroll")
    <meta charset="utf-8"/>
    <meta name="author" content="Paul Vavilov and Vladimir Swirtchkov"/>
    <meta name="description" content="Lecturer's site alpha'">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>@ViewBag.Title</title>
</head>
<body>
<div class="wrapper">
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#b-menu-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Главная", "Index", "Discipline", null, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse" id="b-menu-1">
                <ul class="nav navbar-nav navbar-right">
                    @if ((string)Session["Placement"] == "CourseProjects")
                    {
                        <li class="active">@Html.ActionLink("Курсовые проекты", "Index", "CourseProjects", null, null)</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Курсовые проекты", "Index", "CourseProjects", null, null)</li>
                    }

                    @if ((string)Session["Placement"] == "Disciplines")
                    {
                        <li class="active">@Html.ActionLink("Дисциплины", "Index", "Discipline", null, null)</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Дисциплины", "Index", "Discipline", null, null)</li>
                    }

                    @if ((string)Session["Placement"] == "Groups")
                    {
                        <li class="active"> @Html.ActionLink("Группы", "Index", "Groups", null, null) </li>
                    }
                    else
                    {
                        <li> @Html.ActionLink("Группы", "Index", "Groups", null, null) </li>
                    }

                    @if ((string)Session["Placement"] == "Controls")
                    {
                        <li class="active"> @Html.ActionLink("Контроли", "Index", "Controls", null, null) </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Контроли", "Index", "Controls", null, null)</li>
                    }

                    @if ((string)Session["Placement"] == "Literature")
                    {
                        <li class="active"> @Html.ActionLink("Литература", "Index", "Literature", null, null) </li>
                    }
                    else
                    {
                        <li> @Html.ActionLink("Литература", "Index", "Literature", null, null) </li>
                    }

                    @if ((string)Session["Placement"] == "Lecturers")
                    {
                        <li class="active"> @Html.ActionLink("Преподаватели", "Index", "Lecturers", null, null) </li>
                    }
                    else
                    {
                        <li> @Html.ActionLink("Преподаватели", "Index", "Lecturers", null, null) </li>
                    }
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="margin-top-5 margin-bottom-0 page-header text-center default-cursor">Логин: <span class="login-stuff">@login</span></li>
                            <li class="margin-top-5"><a href="/Account/UserPage">Профиль</a></li>
                            <li><a href="/Account/LogOff">Выйти</a></li>
                        </ul>
                    </li>

                    @if ((string)Session["Type"] == "ADMIN")
                    {
                            <li><a class="glyphicon glyphicon-cog margin-top-minus-3px" href="/Config/Admin"></a></li>
                    }

                </ul>
            </div> <!-- /.nav-collapse -->
        </div> <!-- /.container -->
    </div> <!-- /.navbar -->
    <!-- slider -->
    <div id="slider" class="carousel slide" data-ride="carousel">
        <!-- controls -->
        <ol class="carousel-indicators">
            <li data-target="#slider" data-slide-to="0" class=""></li>
            <li data-target="#slider" data-slide-to="1" class="active"></li>
            <li data-target="#slider" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner">
            <!-- slides -->
            <div class="item active">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>Бета-тест</h1>
                        <p>
                            В данный момент проект находится в стадии бета-тестирования. Вы можете помочь его развитию, уведомляя техподдержку о любых найденных проблемах. Также приветствуется конструктивная критика.
                        </p>
                        @*<p>
                            <a class="btn btn-lg btn-default" href="#" role="button">Button 1</a>
                        </p>*@
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>Техподдержка</h1>
                        <p><a href="mailto:pv.unnamed@gmail.com">pv.unnamed@gmail.com</a></p>
                        <p><a href="mailto:napoleon.emperor@mail.ru">napoleon.emperor@mail.ru</a></p>
                        @*<p>
                            <a class="btn btn-lg btn-primary" href="#" role="button">Button 2</a>
                        </p>*@
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>Финансовая поддержка</h1>
                        <p>
                            В данный момент команда проекта испытывает финансовые трудности. Вы можете поддержать их с помощью кошельков WebMoney:
                        </p>
                        <p>WMZ: Z897510400525</p>
                        <p>WMU: U333583950473</p>
                        @*<p>
                            <a class="btn btn-lg btn-warning" href="#" role="button">Button 3</a>
                        </p>*@
                    </div>
                </div>
            </div>
        </div>
        <!-- left-right controls -->
        <a class="left carousel-control" href="#slider" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
        <a class="right carousel-control" href="#slider" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>
    <main class="container">
        @RenderBody()
    </main>
</div>

<footer class="footer navbar navbar-default">
    <div class="text-center">
        <p class="navbar-text my-nav-text">&copy Vavilov & Swerchkov Ltd 2015-2016</p>
        <p class="navbar-text my-nav-text">All rights reserved. @Html.ActionLink("About", "About", "Shared", null, null) </p>
    </div>
</footer>
</body>
</html>

NureLecturerManager.WEB/Views/Shared/_UserLayout.cshtml
@using NLM.BLL.DTO
@{
    Layout = null;

    UserDTO user = (UserDTO)Session["User"];
    String login = user.Login;
}

@{Html.EnableClientValidation(true);}
@{Html.EnableUnobtrusiveJavaScript(true);}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="author" content="Paul Vavilov and Vladimir Swertchkov" />
    <meta name="description" content="Lecturer's site alpha'">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Профиль</title>
    @Styles.Render("~/Content/css")
</head>
<body>
<div class="wrapper">
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#b-menu-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Главная", "Index", "Discipline", null, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse" id="b-menu-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Курсовые проекты", "Index", "CourseProjects", null, null)</li>
                    <li>@Html.ActionLink("Дисциплины", "Index", "Discipline", null, null)</li>
                    <li> @Html.ActionLink("Группы", "Index", "Groups", null, null) </li>
                    <li>@Html.ActionLink("Контроли", "Index", "Controls", null, null)</li>
                    <li> @Html.ActionLink("Литература", "Index", "Literature", null, null) </li>
                    <li> @Html.ActionLink("Преподаватели", "Index", "Lecturers", null, null) </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="margin-top-5 margin-bottom-0 page-header text-center default-cursor">Логин: <span class="login-stuff">@login</span></li>
                            <li class="margin-top-5"><a href="/Account/UserPage">Профиль</a></li>
                            <li><a href="/Account/LogOff">Выйти</a></li>
                        </ul>
                    </li>
                </ul>
            </div> <!-- /.nav-collapse -->
        </div> <!-- /.container -->
    </div> <!-- /.navbar -->
    <main class="container">
        @RenderBody()
    </main>
</div>

<footer class="footer navbar navbar-default">
    <div class="text-center">
        <p class="navbar-text my-nav-text">&copy Vavilov & Swerchkov Ltd 2015-2016</p>
        <p class="navbar-text my-nav-text">All rights reserved. @Html.ActionLink("About", "About", "Shared", null, null) </p>
    </div>
</footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("/Scripts/jquery.unobtrusive-ajax.js")"></script>

    @if ((string)Session["Type"] != "Студент")
    {
        @Scripts.Render("~/bundles/userPage")
    }

</body>
</html>